### merge and join

In [20]:
df1 = pd.DataFrame({'ID':[1,2,3],
                   'Name':['Alice','John','Bob']})
df1

   ID   Name
0   1  Alice
1   2   John
2   3    Bob

In [21]:
df2 = pd.DataFrame({'ID':[2,3,4],
                   'Score':[50,40,70]})
df2

   ID  Score
0   2     50
1   3     40
2   4     70

In [28]:
#merge merge table using column
merge_data = pd.merge(df1,df2, on='ID',how = 'left')
# merge_data = pd.merge(df1,df2, on='ID',how = 'outer')
# merge_data = pd.merge(df1,df2, on='ID',how = 'left')
merge_data

   ID   Name  Score
0   1  Alice    NaN
1   2   John   50.0
2   3    Bob   40.0

In [29]:
#join join table using index
data1 = pd.DataFrame({'Name':['Alice','John','Bob']},index =[1,2,3])
data2 = pd.DataFrame({'Score':[50,40,70]},index = [2,3,4])
join_data = data1.join(data2, how='outer')
# join_data = data1.join(data2, how='left')
# join_data = data1.join(data2, how='inner')

join_data

    Name  Score
1  Alice    NaN
2   John   50.0
3    Bob   40.0
4    NaN   70.0

### Where Function

In [78]:
import pandas as pd
import numpy as np

df = pd.read_csv('diamonds.csv')

df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [49]:
# df["New"] = np.where(df['cut']=="Good", "Yes","No")
# df["New"] = np.where((df['cut']=="Good")|(df['cut']=="Ideal"), "Yes","No")
df["New"] = np.where(df['color'].isin(['D','E']), "Yes","No")

df.head(10)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,New
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Yes
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Yes
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Yes
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,No
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,No
5,6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,No
6,7,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47,No
7,8,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53,No
8,9,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49,Yes
9,10,0.23,Very Good,H,VS1,59.4,61.0,338,4.00,4.05,2.39,No

In [65]:
# df["New_price"] = np.where(df['color'].isin(['I','J']),df['price']*2,df['price'])
# df["New_price"] = np.where((df['color'] == 'D') & (df['cut'] == 'Premium') ,df['price']*2,df['price'])
df["New_price"] = np.where((df['color'] == 'D') & (df['cut'] == 'Premium') ,df['price']*2,df['price'])
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,New_price
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,326
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,326
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,327
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,334
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,335
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,2757
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,2757
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,2757
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,2757
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,2757

In [81]:
df['Depth_Between'] = np.where(df['depth']<60,"Less then 60",
                      np.where(df['depth']<65,"60-65",
                      np.where(df['depth']<70,"65-70","More then 70")))
df.loc[100:500]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Depth_Between
100,101,0.75,Very Good,D,SI1,63.2,56.0,2760,5.80,5.75,3.65,60-65
101,102,0.75,Premium,E,SI1,59.9,54.0,2760,6.00,5.96,3.58,Less then 60
102,103,0.74,Ideal,G,SI1,61.6,55.0,2760,5.80,5.85,3.59,60-65
103,104,0.75,Premium,G,VS2,61.7,58.0,2760,5.85,5.79,3.59,60-65
104,105,0.80,Ideal,I,VS1,62.9,56.0,2760,5.94,5.87,3.72,60-65
...,...,...,...,...,...,...,...,...,...,...,...,...
496,497,0.71,Premium,D,SI1,61.3,58.0,2822,5.75,5.73,3.52,60-65
497,498,0.70,Premium,D,SI1,60.2,60.0,2822,5.82,5.75,3.48,60-65
498,499,0.70,Ideal,D,SI1,60.7,56.0,2822,5.75,5.72,3.48,60-65
499,500,0.90,Good,J,VS2,64.0,61.0,2822,6.04,6.03,3.86,60-65
500,501,0.71,Ideal,D,SI1,60.2,56.0,2822,5.86,5.83,3.52,60-65